### PR TITLE
Add a missing podcast attribute `itunes_complete` to ITunesRSS

### PR DESCRIPTION
**Pull request by knu**
It is documented here: https://help.apple.com/itc/podcasts_connect/#/itcb54353390

### CODE REVIEW

**Comment by HParker** [comment]
Hey @knu thanks for the PR! Looks straightforward, but do you think you could provide a test for this new key as well?

Also I am going to see if there is anything we can do about the danger failure.

**Comment by HParker** [comment]
Danger is now disabled in master, so you should be able to rebase master in and the build will pass.

**Comment by knu** [comment]
It turned out it was actually a tag for the channel section, so I fixed it and added a spec.

**Comment by HParker** [comment]
Great thank you again!

**Comment by knu** [comment]
Great, thanks for helping me double-check the implementation!

**Pull request merged**
