### PR TITLE
Fix feedburner url

### LINKED ISSUE #327: atom feedburner seems to miss `link` url
AtomFeedBurner seems to be missing the `url` (not `feed_url`) for a feed. I think because it's looking for `element :link, :as => :url, :value => :href, :with => {:type => "text/html"}`, but feedburner is not (no longer?) putting the `type='text/html'` on the `link` tag anymore, at least for some feeds. 

I'm trying to figure out how to customize/monkey-patch this locally, but haven't gotten it yet.  I'm not sure if it should be fixed in master,  if it's a universal problem.  I'm not sure if there's any good way to get SaxParser to use the first link found if no link with proper type attribute is found.

### PR DESCRIPTION
**Pull request by amatriain**
Fixes #327 

Changed AtomFeedBurner parser so that it correctly parses feedburner atom feeds in the new style some feeds seem to be using. In this alternate style:

- the link to the feed webpage may be a plain ```<link>``` element without the type="text/html" attribute we usually expected

- the link to the feed itself may be a ```<atom10:link>``` element instead of the ```<link>``` element we usually expected (with type="application/atom+xml")

The way the change is implemented, old-style values will take precedence if present in the feed. Only if the new style is used will the parser use the new locations for the url and feed_url values.

### CODE REVIEW

**Comment by amatriain** [comment]
Getting the PR accepted by Danger has been painful. Couldn't some of the validations be relaxed? I don't think rejecting a PR because of a commit message longer than 50 chars, or ending in a period, is a good idea.

Also if e.g. Danger rejects a PR because a commit message is too long, is there any way to make it pass short of closing the PR, rewriting commit history and submitting a new PR? Because I haven't found any, and that makes unnecessary noise.

**Comment by jonallured** [comment]
@amatriain I'm sorry you've found Danger annoying - you are not the first that this has happened to. I'm going to be working on improving the feedback the bot gives, so hopefully I can address your concerns that the group will want to continue using it.

**Comment by HParker** [comment]
Makes sense to me and good tests!

Best reference I can find to `atom10:link` is here:
https://github.com/gpodder/podcast-feed-best-practice/blob/master/podcast-feed-best-practice.md#link

Do you know where it is defined in a spec/rfc?

**Comment by amatriain** [comment]
@HParker it seems to be just an atom 1.0 namespace, but I can't find a spec document either. It can be found in use in the wild however.

**Comment by HParker** [comment]
Sorry this is happening slowly. There is still a bit of discussion around what "out of spec" things we want to support and what exactly _is_ in and out of spec for feedjira.

This is one of those things where I am not sure if we should support it, or suggest a custom parser.

I would love your thoughts on this.

**Comment by amatriain** [comment]
Is ```atom10:link``` really out of spec, though? As far as I can tell the use of XML namespaces in feeds is according to spec but optional.

It's interesting to look at what the W3C has to say about one of these feeds:

[W3C validation of GiantRobotsSmashingIntoOtherGiantRobots feed](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Ffeeds.feedburner.com%2FGiantRobotsSmashingIntoOtherGiantRobots)

Right at the top the validator says:

```This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations - Avoid Namespace Prefix: atom10```

So it's a valid feed and any issues with it may come from feed parsers that don't support the correct but uncommon practice of using XML namespaces.

Also the validator links to a page [explaining why they suggest not using namespaces](https://validator.w3.org/feed/docs/warning/AvoidNamespacePrefix.html). It's clear they consider it a valid practice but advise against it because many parsers do not support it. So I think there's no harm in supporting it in Feedjira.

**Comment by HParker** [comment]
Thanks for clearing that up!

**Pull request merged**
