### PR TITLE
update changelog and bump version

### PR DESCRIPTION
**Pull request by HParker**
We have a healthy list of authors this release,

@jfiorato
@krasnoukhov
@PascalTurbo
@sferik
@knu

Thanks so much for your work improving Feedjira. Assuming the build comes back green I propose we call this 2.1.0 tomorrow. Any objections?

### CODE REVIEW

**Comment by sferik** [comment]
Yay! I have one more incoming PR to parse <image> elements in RSS and iTunes RSS feeds. I’ll be opening that momentarily.

**Comment by HParker** [comment]
One day I'll learn to start my commit messages with a capital letter. thank you FeedjiraBot.

@sferik Cool, feel free to ping me when you are ready.

**Comment by sferik** [comment]
@HParker Please review: https://github.com/feedjira/feedjira/pull/349.

**Comment by HParker** [comment]
@jonallured I don't think I have permissions to release a new version of feedjira. If this looks about right, do you think you could push the button for us?

**Comment by jonallured** [comment]
Heyo! I just added @HParker as an owner - looks like you guys are doing great work, thanks for making it happen!! ❤️ ❤️ ❤️

**Comment by knu** [comment]
Glad to see that the project still moving forward with this many contibutors and maintainers involved! 👍

**Comment by HParker** [comment]
https://rubygems.org/gems/feedjira/versions/2.1.0

**Pull request merged**
