### PR TITLE
Implement support for Atypon RSS feeds

### LINKED ISSUE #246: RDF Feed with prefixed tags fails to parse
Here is the example feed:

http://www.tandfonline.com/action/showFeed?ui=0&mi=el63dh&ai=1dl&jc=wjwl20&type=etoc&feed=rss

Obviously, it's perfectly legit to prefix any element in an XML doc. However, SAXMachine doesn't seem to really handle this well, and I think one of the reasons the ATOM preprocessor calls `Nokogiri::XML#.remove_namespaces!` for Feedburner. 

Not sure of the best way to handle this one. Options might be, but are not limited to:
 - Detect the namespace with a regex, and if it exists then use a different parser class that will strip the namespaces.
 - Detect the namespace with a regex, and if it exists then strip that specific namespace and use the existing RSS parser.
 - Do nothing and shame people for the superfluous use of xml prefixes.

Any thoughts on this one? I'm happy to put together the fix once we decide on the right way to do it.

### PR DESCRIPTION
**Pull request by jfiorato**
Fixes #246

### CODE REVIEW

**Comment by jfiorato** [comment]
@HParker Sorry I didn't get this in before 2.1

**Comment by mikeastock** [comment]
@jfiorato how do you feel about moving this parser to it's own gem?

**Comment by jfiorato** [comment]
That's perfect. I'll do that. Thanks!

**Comment by jfiorato** [comment]
@mikeastock Is there a proper naming convention for custom parser gems?
`feedjira-atypon`
`feedjira-parser-atypon`

**Comment by mikeastock** [comment]
@jfiorato we don't have a convention yet but I would probably vote for the shorter name. `feedjira-atypon`

**Comment by jfiorato** [comment]
Closing PR. Changes will go in custom parser gem.

**Comment by mikeastock** [comment]
@jfiorato once you have the gem created let us know and we can link to it from the README

**Comment by jfiorato** [comment]
Custom parser gem for these types of feeds is located here: https://github.com/theoldreader/feedjira-atypon

**Pull request closed without merging**
