### PR TITLE
Add support for the Google Alerts feed format

### PR DESCRIPTION
**Pull request by knu**
It is essentially a normal Atom feed with Google redirector URLs.  The AtomGoogleAlertsEntry class extracts the original URL from each redirector URL.

Their feeds contain HTML titles, so this PR is marked as WIP pending https://github.com/feedjira/feedjira/pull/423.

### CODE REVIEW

**Comment by HParker** [comment]
Thanks for this @knu If you don't mind resolving the build and adding a changelog entry, I'll be happy to merge. 👍

**Comment by knu** [comment]
I'll rebase after #423 gets merged.

**Comment by knu** [comment]
@HParker This one is ready too!

**Comment by knu** [comment]
I didn't know 3.0.0 was already out when I was working on this.  The CHANGELOG entries I added should belong to a new section (3.0.1?).  Also, adding a tag for 3.0.0 would be nice.

**Comment by HParker** [comment]
@knu great idea! I am also going to add you as a maintainer. Don't feel any pressure to do extra work you don't want to, but hopefully this means I won't slow you down too much. :)

**Comment by knu** [comment]
Thanks!  I've been using and relying on this library for quite a while now.  I'll be working on it from time to time, dealing with open issues and probably reducing my local patches.

**Pull request merged**
