### PR TITLE
Add support for older faraday versions

### PR DESCRIPTION
**Pull request by davoclavo**
Currently feedjira only supports Faraday 0.9 but should work with 0.7.4, 0.8 and 0.9 - A lot of applications don't have the most updated set of gems, so why not let them use the fearless feedjira 2.0.0!

Added the [appraisal gem](https://github.com/thoughtbot/appraisal) so tests can be run against different versions of dependencies.

First install the various gemsets

`appraisal install`

then, to run tests against the different faraday versions:

`appraisal rake`

### CODE REVIEW

**Comment by amatriain** [comment]
Personally I'm against having to pull Appraisal as an additional dependency in all projects that use Feedjira. I vote for rejecting this PR, for whatever it's worth.

The advantages brought by this PR (supporting older Faraday versions) are IMHO clearly outweighted by having a gem I don't want nor need pulled into my bundle.

Also, Faraday 0.9 (which Feedjira currently supports) was released in **January 2014**. Over a year and a half ago. Faraday 0.8 (the newest release this PR would add support for) was released in **May 2012**. That's ages in ruby time. Backward compatibility is good, but adding noise to the bundle only to support *ancient* Faraday versions is clearly not worth it.

**Comment by davoclavo** [comment]
The Appraisal gem is only listed in the Gemfile, so it used only for development. It is not listed as part of its runtime dependencies, so you wouldn't have to install it in projects that use Feedjira.

I think there are benefits on supporting at least 0.8 (maybe we could drop 0.7). Several projects that were developed in the last years are stuck with gems that depend on Faraday 0.8, which means they are not able to use Feedjira 2.0.0. The current solutions are either fork the repo and add support to 0.8, or keep the old version that uses Curl as an HTTP client (which is the main benefit of 2.0.0).

Additionally, Faraday 0.8.9 was released on **Jan 2014**, I don't think that's *ancient* in terms of development cycles. Take a look at [faraday_middleware dependencies](https://rubygems.org/gems/faraday_middleware/versions/0.10.0), it supports Faraday 0.7.4 - 0.9 for a reason.

**Comment by amatriain** [comment]
@davoclavo it seems that I had a flawed understanding of how the Gemfile works in gem development. Sorry about that.

I withdraw my objections.

**Comment by davoclavo** [comment]
@amatriain don't worry! Also I think I should move it to the gemspec file instead, as a `gem.add_development_dependency`, to avoid having to depend on bundler.

**Comment by HParker** [comment]
Thanks @davoclavo! I really like this change. I pulled it down to try it out and everything seems to work except the recent addition of `danger-commit_lint` wants (~> 0.9). I am worried at this point it makes more sense to only support 0.9 since that covers all the releases since 2014.

I am going to close, but feel free to let me know if you still feel strongly that we should support versions older than 0.9.

**Pull request closed without merging**
