### PR TITLE
Oga SAX handler

### PR DESCRIPTION
**Pull request by krasnoukhov**
Since https://github.com/feedjira/feedjira/pull/254 things were improved, so here it goes. It's now possible to use Feedjira with Oga as a backend. Please note that I had to convert line endings because of differences in handling of these by backends. I hope that is fine with you @jonallured!

Let me know what you think. Thanks!

### CODE REVIEW

**Comment by fudanchii** [comment]
I can also confirm that all the tests is working fine with Oga on jruby. :+1:

**Comment by HParker** [comment]
Hey @krasnoukhov I resolved the conflicts and pushed up the changes here: https://github.com/feedjira/feedjira/compare/master...HParker:krasnoukhov-oga?expand=1

If you are still interested in this PR, I think we could merge it. What do you think?

**Comment by HParker** [comment]
Eh, I realized I was going to have to fight the build a little, so I created a new PR here: https://github.com/feedjira/feedjira/pull/331

**Comment by krasnoukhov** [comment]
@HParker I just updated this PR. I'd prefer if you merged danger change into a master first, so I can rebase once more to get this build green and merged. What do you think?

**Comment by HParker** [comment]
Yeah, sounds like a plan!

**Comment by HParker** [comment]
Great, should be ready for a rebase whenever you get a chance.

**Comment by krasnoukhov** [comment]
@HParker All ready. Thanks

**Comment by HParker** [comment]
Awesome thanks!
Pulled it down and worked with it locally, seems to work great!

 I think the next step here will be updating the docs to show this as the recommended way to use feedjira with jruby-9. I would be excited to see that pull request if you are interested.

**Comment by krasnoukhov** [comment]
I don't really use sax-machine/feedjira much these days, so I'll have to pass, thanks

**Comment by HParker** [comment]
No problem, thanks for this PR.

**Pull request merged**
