### PR TITLE
Images from 'media:thumbnail'

### PR DESCRIPTION
**Pull request by eksoverzero**

### CODE REVIEW

**Comment by HParker** [comment]
Looks like the build is complaining. If you don't mind looking into that and adding some tests with an example feed, I would be happy to merge this.

**Comment by eksoverzero** [comment]
Hey, @HParker. Yeah, this is Rubocop complaining about all sorts of things from the entire project. I have 0.5.4 installed. I'm going to update the existing code base for this version in a new branch, if that's okay?

**Comment by HParker** [comment]
Oh, I see the rubocop version changed under us and it is just complaining on your PR.

Yeah, if you are interested in taking that on, go for it, otherwise I can take a look soon.

**Comment by HParker** [comment]
Actually, one more thing before we merge this, can you add a spec that exercises the new code and merge master?

**Comment by HParker** [comment]
Fixed the rubocop warning and merged. Thanks @eksoverzero for the change!

**Pull request merged**
