### PR TITLE
bump version

### PR DESCRIPTION
**Pull request by mockdeep**
update changelog,

### CODE REVIEW

**Comment by mockdeep** [comment]
@HParker would you mind releasing this version?

**Comment by HParker** [comment]
Sure! thanks for putting it together. ❤️

**Comment by HParker** [comment]
Released! https://rubygems.org/gems/feedjira thanks @mockdeep!

@mockdeep I also added you as a owner on ruby gems so if I disappear for too long, you can continue the project. ❤️ Thanks or your hard work. Please confirm you got the invitation and I got the email correct.

**Comment by mockdeep** [comment]
Thanks @HParker I got the invite!

**Pull request merged**
