### PR TITLE
Add configuration for stripping whitespace from XML

### PR DESCRIPTION
**Pull request by mikeastock**
This is intended to resolve https://github.com/feedjira/feedjira/issues/350 by giving users the option to tell Feedjira to strip all whitespace

### CODE REVIEW

**Comment by PascalTurbo** [comment]
Now we got two configurations ^^
Maybe you could wait until #357 is merged and than use that Config for your PR. Please add some Code Documentation, also (on method level - not only on module level).

**Comment by HParker** [comment]
@PascalTurbo This implementation is significantly simpler, do you think we can merge this first, then bring your logging stuff on top of it?

**Comment by HParker** [comment]
Yeah, is our rubocop version out of date? It seems to be making different recommendations around comments than I would expect.

**Comment by PascalTurbo** [comment]
@HParker This solution isn't really simpler than mine but I love the idea using extend over using Module Chaining. 
Because this commit isn't mergeable at the moment and there will be more work on my side than on @mikeastocks side I would go a third way: Adopting the implementation of @mikeastock and after doing this he could add the stripping methods. For sure I will only do this if @mikeastock agrees with this.

**Comment by PascalTurbo** [comment]
@HParker maybe your confusion is related to #345. I've enabled checks for class, module and method documentation (and found this confusing rubocop bug https://github.com/bbatsov/rubocop/issues/3807)

**Comment by HParker** [comment]
> maybe your confusion is related to #345
Ah, that would do it!

@mikeastock what do you think of @PascalTurbo's proposal?

**Comment by mikeastock** [comment]
I've added documentation to this PR. Could we merge this first? @PascalTurbo I'm totally down to change your branch to work with the config from here.

**Comment by HParker** [comment]
Checks are passing, I say we keep moving forward.

**Pull request merged**
