### PR TITLE
Remove dependency restrictions

### PR DESCRIPTION
**Pull request by jonallured**
The latest and greatest is working just fine.

### CODE REVIEW

**Comment by jrochkind** [comment]
Locking to major versions is a good idea, since things doing semver will do backwards breaking changes on major version updates. I'd suggest updating the major version locked to if there's a new one that works fine, but not removing version requirements entirely. 

Not sure if this is being maintained by anyone anymore though?

**Comment by jonallured** [comment]
Hi @jrochkind, I am the maintainer of Feedjira. I saw your comments come in last night and they made me feel bad because you're right that I haven't done a good enough job maintaining this gem lately. The reality is that I don't actually use this project anymore and there isn't anyone else with commit access paying attention.

I believe that it's important in open source to assume the best of people, so I'm going to assume you're a nice person and your comments are coming from a place of frustration. I'm going to assume that you did not intend to hurt my feelings or make me feel bad because that's what I'd want if I was frustrated with a project. Sorry things aren't in a little better shape around here, but if you want, you can help!

I have just opened up #324 - it's an issue where I've invited people to comment if they'd like commit access to this repo. I hope that people will take me up on it, but if not I'll keep trying to find time to work on the gem.

Finally, @jrochkind, I hope you take this comment the way it was intended - a little venting on my part about how it can be really hard to maintain open source projects. If you want commit access, please comment on #324, but don't feel like you have to. Take it from me, it's a lot of work! :smile:

**Comment by jrochkind** [comment]
Sorry, I intended it only as the question it was -- more information about the current maintenance status of this project. I am considering using feedjira for a project, and whenever I consider that, I review the open issues and PRs and latest commits and try to get a sense of the current maintenance of the project. In this case, I wasn't really sure -- there was some recent activity, but also lots of pretty old PR's that seemed good but were unmerged. So I asked. 

Thanks for the response. In the future I'll try to be more sensitive when I ask that. 

If I end up going forward using feedjirra, and have things I need changed about it, I will definitely consider volunteering to help with some maintenance.

**Comment by HParker** [comment]
Merged via #341

**Pull request closed without merging**
