### PR TITLE
Fix `itunes_categories` and add `itunes_category_paths`

### PR DESCRIPTION
**Pull request by knu**
`itunes_categories` no longer includes the contents of the text nodes inside of `<itunes:category>` elements when using the Nokogiri handler.

`itunes_category_paths` contains an array of arrays that hold all category-subcategory paths.

### CODE REVIEW

**Comment by HParker** [comment]
Thanks for the PR! I believe rebasing master in and fixing the style issues should fix the build. Do you have a link to this part of the iTunes docs as well? that was helpful in the other PR.

**Comment by knu** [comment]
The latest specification is here: https://help.apple.com/itc/podcasts_connect/#/itcb54353390
The names of the subcategories are all unique to each other, so `itunes_categories` should be enough for filtering, but if you want to categorize podcast feeds, `itunes_category_paths` is useful.

**Comment by HParker** [comment]
Great thanks! Sorry that the Rubocop nonsense is getting you down. :(

I am probably going to start getting notes together to release a version including these changes this weekend.

**Comment by knu** [comment]
Thanks!  Looking forward to the first minor new release from the 2.0 series, which will make us users confident in using it for a long term.

**Pull request merged**
